### PR TITLE
Fix tests on Python 3.5

### PR DESCRIPTION
**Pull request by gforcada**
master branch coming from https://github.com/pyrenees/plone.alterego to add python 3.5 compatibility.

@datakurre I cleanup the commits to remove buildout/boostrap and all that. Is it worth keeping?

### CODE REVIEW

**Comment by davisagli** [comment]
As we're adding Python 3 compatibility to packages I would like to make sure that we set them up to run CI on Python 3 (so that further work in Python 2 doesn't accidentally break things). Thoughts on whether it makes more sense to add a Python 3 pull request job on Jenkins that only includes the packages we've worked on porting, or does it make more sense to set up CI per-package on another system like Travis?

The actual changes here mostly LGTM, though the approach for dealing with different doctest output in Python 2 vs 3 is a bit hokey...I think it'd be better to rewrite as non-doctests.

**Comment by datakurre** [comment]
I agree that rewriting doctests into unit tests would be better, but for me it was easier to do one thing at time: fix Py 3 issues now (we needed Py 3 support) and fix doctests into unit tests later. The latter requires more thinking, because the doc part of doctests should be preserved.

**Comment by davisagli** [comment]
Sure, I don't consider rewriting as unit tests to be a blocker for merging this.

**Comment by davisagli** [comment]
Closing in favor of #4

**Pull request closed without merging**
