### PR TITLE
Add python 3 compatibility

### PR DESCRIPTION
**Pull request by davisagli**
This is like #2 but includes travis configuration and is rebased on current master.

### CODE REVIEW

**Comment by gforcada** [comment]
As for CI (jenkins.plone.org) I do have the plan to bring that in (single packages tests) so we can check that on 2.7 the integration still works and that the single package tests do work as well on py3.

For that, would it be a good idea already to just pip install zc.buildout and get rid, once and for all, of bootstrap.py? Pretty please?

**Comment by davisagli** [comment]
That sounds good...do you know what are the commands we need to run to bootstrap then?

**Comment by gforcada** [comment]
@davisagli with:

```
virtualenv-2.7 .
source bin/activate
pip install zc.buildout
buildout
```

Should be enough. Replace ``virtualenv-2.7`` by ``pyvenv`` for a python 3 virtualenv.

**Comment by jensens** [comment]
more robust is imo 

```
virtualenv-2.7 .
./bin/pip install zc.buildout
./bin/buildout
```

but both works. Latter works also w/o activate in any case.

**Comment by jensens** [comment]
jenkins build fails after merge

**Pull request merged**
